SHUTDOWN_MSG = "shutdown"
OPEN_MSG = "shutdown"
MQTT_BROKER_IP = "127.0.0.1"
MQTT_BROKER_PORT = 1883
MUSEUM_TOPIC = "museum_name"
MUSEUM_GENERAL_TOPIC = MUSEUM_TOPIC + "_all"

FLASH_TOPIC_PATH = "/flash"
